### ISSUE TITLE
Module 'spendb.templates' is not available

### ISSUE THREAD

**Issue by holgerd77** [spendb/spendb.ui#1]
Hi Friedrich, I managed to install all the dependencies with `npm` and `bower`, but now I am stuck at this point. Any suggestions?

Holger-Drewess-MacBook-Air-3:spendb.ui hdrewes$ node_modules/karma/bin/karma start --single-run --browsers PhantomJS karma.conf.js
WARN [watcher]: Pattern "/Users/hdrewes/Documents/DEV/SpenDB/spendb.ui/bower_components/vega-lite/vega-lite.js" does not match any file.
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket 7WN2Ggz-Tu_JxcK5SgxF with id 18173579
PhantomJS 1.9.8 (Mac OS X 0.0.0) styleHelper "before each" hook: workFn FAILED
    Error: [$injector:modulerr] Failed to instantiate module spendb due to:
    Error: [$injector:modulerr] Failed to instantiate module spendb.templates due to:
    Error: [$injector:nomod] Module 'spendb.templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
    http://errors.angularjs.org/1.2.28/$injector/nomod?p0=spendb.templates
        at /Users/hdrewes/Documents/DEV/SpenDB/spendb.ui/bower_components/angular/angular.js:1679
        at ensure (/Users/hdrewes/Documents/DEV/SpenDB/spendb.ui/bower_components/angular/angular.js:1601)
        at module (/Users/hdrewes/Documents/DEV/SpenDB/spendb.ui/bower_components/angular/angular.js:1892)
        at /Users/hdrewes/Documents/DEV/SpenDB/spendb.ui/bower_components/angular/angular.js:3877

**Comment by pudo** [comment]
Hm, not sure. Did you run grunt before running the tests?

**Comment by holgerd77** [comment]
Ah, my intention actually was not to run tests but the application itself,
thought Karma was used for this cause I didn't find an index.html file or
similar as an entry point.

Yes, I run node and grunt install and figured out that the important stuff
is put into the build directory.
Am 19.08.2015 08:36 schrieb "Friedrich Lindenberg" <notifications@github.com

**Comment by pudo** [comment]
No, unfortunately, the application can only be run from inside the Python application, since it relies on the API being present on the local path. That would be a very cool thing to change, though.
