### ISSUE TITLE
"grant link spendb.ui" command in Wiki source install instructions not working

### ISSUE THREAD

**Issue by holgerd77** [spendb/spendb.ui#2]
See wiki:
https://github.com/spendb/spendb/wiki/Developer-installation#installation-from-source

Could make the the connection to this Grunt task library:
https://github.com/doug-martin/grunt-link

Not sure though, is this deprecated or are some Grunt configuration parts missing?

**Comment by pudo** [comment]
Oops it was meant to be `bower link`, not `grunt link`. Fixed.

**Comment by holgerd77** [comment]
Now there is double `bower link`. Which one is the better? :-)

**Comment by pudo** [comment]
It's a [very odd command](http://bower.io/docs/api/#link): if you run `bower link` without an argument it'll announce that there's a development version of the library available in the current directory. `bower link module` then links that announced version into an app depending on it.

**Comment by holgerd77** [comment]
So this sequence of instructions from the wiki is correct?

$ git clone http://github.com/spendb/spendb.ui.git
$ cd spendb.ui
$ npm install
$ bower install
$ grunt
$ bower link
$ cd ..
$ bower link spendb.ui

2015-09-03 10:30 GMT+02:00 Friedrich Lindenberg notifications@github.com:
